#
# Copyright (C) 2024 nosignals https://github.com/nosignals
# https://github.com/armarchindo/ULO-Builder
# https://github.com/sib0ndt
# https://github.com/Haris131
# Tukang copas 😁 BobbyUnkown https://github.com/bobbyunknown
# 
name: ULO Autobuilder

on:
  workflow_dispatch:

jobs: 
  build_ipk:
    permissions:
      contents: write
      actions: write
    name: ULO Autobuilder
    runs-on: ubuntu-latest
    steps:
      
      - name: Memperbarui dan Memasang Dependensi
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install lolcat build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget pigz aria2 tree
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Atur izin
        run: |
          chmod 775 ulo build.sh

      - name: Unduh dan ekstrak ULO repository
        run: |
          echo "Mengunduh ULO repository..."
          curl -L https://github.com/bobbyunknown/ULO-repository/archive/refs/heads/main.zip -o ulo-repo.zip
          
          echo "Mengekstrak ULO repository..."
          unzip ulo-repo.zip
          
          echo "Memindahkan file-file ke struktur yang diharapkan..."
          mv ULO-repository-main/kernel ./core/
          mv ULO-repository-main/rootfs/* ./rootfs/
          mv ULO-repository-main/firmware ./core/root/lib/
          
          echo "Membersihkan file sementara..."
          rm -rf ULO-repository-main ulo-repo.zip
          
          echo "Struktur direktori setelah ekstraksi ULO repository:"
          ls -R

      - name: Unduh rootfs tambahan
        run: |
          echo "Mulai mengunduh rootfs tambahan..."
          curl -LO https://github.com/sugengtd7/rootfs/releases/download/23.05.05/InsomWRT-OpenWRT-23.05.05-armsr-armv8.tar.gz
          
          echo "Memindahkan rootfs tambahan ke direktori rootfs..."
          mv InsomWRT-OpenWRT-23.05.05-armsr-armv8.tar.gz ./rootfs/
          
          echo "Isi direktori rootfs setelah penambahan:"
          ls -l ./rootfs/

      - name: Menjalankan script    
        run: |
          ./build.sh
          
      - name: Memeriksa struktur direktori keluaran dan ukuran file
        run: |
          echo "Directory structure:"
          tree ./out
          echo "File sizes:"
          find ./out -type f -name "*.img.gz" -exec du -sh {} +
          
      - name: Mengunggah aset rilis
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: out/**/*.img.gz
          tag: firmware-release-${{ github.run_number }}
          overwrite: true
          body: |
            ##  OpenWRT Release for multiple devices
            ULO-Builder Release from Github Workflow
            ## Login
            - user: root
            - pass: dbai
        env:
          ACTIONS_STEP_DEBUG: true
