#
# Copyright (C) 2024 nosignals https://github.com/nosignals
# https://github.com/armarchindo/ULO-Builder
# https://github.com/sib0ndt
# https://github.com/Haris131
# Tukang copas 😁 BobbyUnkown https://github.com/bobbyunknown
# 
name: ULO Autobuilder

on:
  workflow_dispatch:

jobs: 
  build_ipk:
    permissions:
      contents: write
      actions: write
    name: ULO Autobuilder
    runs-on: ubuntu-22.04
    steps:
      
      - name: Memperbarui dan Memasang Dependensi
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install lolcat build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget pigz aria2 tree
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Atur izin
        run: |
          chmod 755 ulo build.sh

      - name: Unduh dan pindahkan rootfs tambahan
        run: |
          echo "Mulai mengunduh rootfs tambahan..."
          curl -LO https://github.com/sugengtd7/rootfs/releases/download/24.05.05/openwrt-24.10.0-rc2-armsr-armv8-generic-rootfs.tar.gz
          
          echo "Membuat direktori rootfs jika belum ada..."
          mkdir -p ./rootfs
          
          echo "Memindahkan rootfs tambahan ke direktori rootfs..."
          mv openwrt-24.10.0-rc2-armsr-armv8-generic-rootfs.tar.gz ./rootfs/
    
      - name: Mengatur tanggal
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Menjalankan script    
        run: |
          ./build.sh
          
      - name: Memeriksa struktur direktori keluaran dan ukuran file
        run: |
          echo "Directory structure:"
          tree ./out
          echo "File sizes:"
          find ./out -type f -name "*.img.gz" -exec du -sh {} +
          
      - name: Mengunggah aset rilis
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: out/**/*.img.gz
          tag: InsomWRT 24.10.0-rc2
          overwrite: true
          body: |
            ##  OpenWRT Release for multiple devices
            ULO-Builder Release dari Github Workflow
            Tanggal Build: ${{ steps.date.outputs.date }}
            ## Login
            - user: root
            - pass: tidakadapassword
            
            ### Amlogic
            s905x (HG680P, B860Hv1/v2)
            s905x2 (HG680FJ, B860Hv5, MNC CYBORG001)
            s905x3 
            s905x4 (AKARI AX810, dll)
            ### Allwinner
            H5 (Orange Pi Zero Plus 2, Orange Pi Zero Plus, Orange Pi Prime, Orange Pi PC2)
            H6 (Orange Pi 1 Plus, Orange Pi Lite 2, Orange Pi 3 LTS, Orange Pi 3)
            H616 (Orange Pi Zero 2)
            H618 (Orange Pi Zero 3, Orange Pi Zero 2W)
            ### Rockchip
            RK3566 (Orange Pi 3B)
            RK3588S (Orange Pi 5)
            RK3588 (Orange Pi 5 Plus)
        env:
          ACTIONS_STEP_DEBUG: true
