#
# Copyright (C) 2024 nosignals https://github.com/nosignals
# https://github.com/armarchindo/ULO-Builder
# https://github.com/sib0ndt
# https://github.com/Haris131
# Tukang copas 😁 BobbyUnkown https://github.com/bobbyunknown
# 
name: ULO Autobuilder

on:
  workflow_dispatch:

jobs: 
  build_ipk:
    permissions:
      contents: write
      actions: write
    name: ULO Autobuilder
    runs-on: ubuntu-latest
    steps:
      
      - name: Update and Install Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install lolcat build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget pigz aria2 tree
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Set permissions
        run: |
          chmod 775 ulo build.sh
      
      - name: Download rootfs
        run: |
          wget https://github.com/sugengtd7/rootfs/releases/download/23.05.05/InsomWRT-OpenWRT-23.05.05-armsr-armv8.tar.gz
          mkdir -p ULO-Builder/rootfs
          mv InsomWRT-OpenWRT-23.05.05-armsr-armv8.tar.gz ULO-Builder/rootfs/
        
      - name: Run Script  
        run: |
          ./build.sh
          
      - name: Check output directory structure and file sizes
        run: |
          echo "Directory structure:"
          tree ./out
          echo "File sizes:"
          find ./out -type f -name "*.img.gz" -exec du -sh {} +
          
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: out/**/*.img.gz
          tag: firmware-release-${{ github.run_number }}
          overwrite: true
          body: |
            ##  OpenWRT Release for multiple devices
            ULO-Builder Release from Github Workflow
            
            ## Login
            - user: root
            - pass: dbai
        env:
          ACTIONS_STEP_DEBUG: true
